version: '2'
services:
  web:
    build: ./flask
    ports:
     - "5000:5000"
    volumes:
     - ./flask:/app
    environment:
     - "PYTHONUNBUFFERED=1"
    restart: always
  redis:
    image: "redis:alpine"
    restart: always
  dns:
    build: ./dns
    tty: true
    ports: 
     - "53535:53/udp"
    restart: always
